### PR TITLE
Added documentation on how to use the AGL Test Framework

### PR DESCRIPTION
**Pull request by CorentinLGS**

### CODE REVIEW

**Review by dl9pf — COMMENTED** [review]
It is the (AGL) *AppFW*  test framework. Not to confuse ppl. Please change that accordingly in the doc. Tnx.

**Comment by claneys** [comment]
We do not want this to be confused with @jobol test about AppFw. This is more a documentation about how to test binding than the AppFw itself.
So may be AGL binding test framework should be better then ?

**Comment by dl9pf** [comment]
So is that meant for the agl-service-* ?

**Comment by sebd71** [comment]
Yes, it's a framework to test agl-service-* bindings. That's why AGL Test Framework or AGL Service Test Framework seems to me the right title for this documentation.

Changes look good for me.

**Comment by CorentinLGS** [comment]
So, do I change the name to AGL Service Test Framework or do I let it as it is now ?

**Pull request merged**
