### PR TITLE
porter-footer.md: Debbuging

### PR DESCRIPTION
**Pull request by leon-anavi**
Add instructions for connecting USB to Micro-B USB
cable to Renesas Porter board for serial
debugging.

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

### CODE REVIEW

**Comment by kooltux** [comment]
Hi Leon.
+1 for me

A question: TL;DR: the organisation of documents and folders should follow the TOC of a whole guide formed by concatenating the MD files.

Why did you separated the "board" document and the "footer" one initially ? I mean: having some generic documents assembled with only one specific may be easier ? 

If you look at a typical website with no merging capability, this forces to create 2 entries in the TOC - see here for example: http://docs.iot.bzh/docs/getting_started/en/dev/ => I had to separate things in 2 sections: "Getting started" and "Known issues". If it's what we want, then renaming the "footers" to "<board>-troubleshooting.md", stored in a "troubleshooting" subfolder would make things clear. 
But Maybe we could simply have a single document for each board and the TOC would be simpler and the reader would have everything related to a given board in the same document. 

Note that your current organisation is ok for me for the webdocs tool I'm working on, as we can merge multiple MD files before generating HTML. But that's not always the case (mkdocs or RTD may not support this). And for maintenance, having the MD files follow roughly the TOC of a full guide is easier. 

I hope I'm clear in my explanations :)

**Comment by leon-anavi** [comment]
Hi @kooltux,

The generic guide for building AGL has the following major sections for each supported hardware platform:
1. Download the source code 
2. Build, flash and boot AGL for the specified platform
3. Troubleshooting
4. Additional notes for the specified platform (for example specific troubleshooting guidelines, remarks and debugging instructions )

The 2nd and 4th section are very specific depending on the hardware therefore I have written them in separated sections in the markdown files from directories machines and footers. This way there is no duplication of information. Script generate-getting-started.sh and pandoc take care of merging all these sections together. 

The final result is a single document with the exact steps for a certain hardware platform. The document is nice and tidy. It is easy to maintain it. There is no copy & paste between different documents. Furthermore it is very convenient for the users because they have the exact steps in a single place.

Best regards, Leon

**Comment by kooltux** [comment]
Hi Leon,

On the website, that's different: we don't want to make a TOC with a section for each board where the generic instructions would be repeated first.

Do we really have to create one document per board or could we have a single document with a generic part at the beginning and 1 section per board after that, containing specific stuff & trouble shooting all stored in a single file ?

I think that using pandoc and a few scripts is just convenient from time to time but not the right solution at the end: the documentation must be handled with a dedicated tool that will handle more than transforming mardown into html or pdf.

So the documentations files should be structured with those publshing tools in mind: whether it's mkdocs, readthedocs or the tool 'webdocs' I'm working on.

BR
Stephane

**Comment by leon-anavi** [comment]
Hi @kooltux,

In my opinion based on my personal experience, it is always easier for the users to have all exact steps in a single document. 

There are very specific instructions for booting, debugging, configuration and troubleshooting for each supported by AGL at the moment.  I expect that over the time AGL will support more and more boards therefore it will be very inconvenient to have a mega document with instructions for all boards. 

I prefer to have a single document with the exact steps for each board that AGL supports. Using markdown files + pandoc seems an easy way to maintain the documentation source splitted over several files and to generate a single document for each board out of it. 

Anyway, this is just my opinion. The discussion about the new organization of the documentation are a bit out of the scope of the patches in this GitHub pull request. I hope the GitHub pull request will be soon merged because it contains valuable technical information.

Thanks, Leon

**Comment by kooltux** [comment]
True: I'm out of scope :)

**Comment by leon-anavi** [comment]
Thanks for merging the changes :) 

Best regards, Leon

**Pull request merged**
