### PR TITLE
Remove dev header and edit button from doc site and update header/footer

### PR DESCRIPTION
**Pull request by dl9pf**
I removed the dev warning,  edit link, language and version selector as we don't use it atm.

Signed-off-by: Jan-Simon Möller <dl9pf@gmx.de>

### CODE REVIEW

**Comment by kooltux** [comment]
I wanted to activate a specific dd branch for doc nect week. Plz wait before merging this one  ; )

**Comment by dl9pf** [comment]
Ping ;)

**Comment by kooltux** [comment]
SPEC-953 is not started yet... Let's hold this PR some more time.

**Comment by dl9pf** [comment]
Ping again. Lets get rid of the header. The SPEC-953 in all glory with branches needs more time .

**Review by kooltux — APPROVED** [review]
OK to remove that, except maybe the edit link which can be convenient for md files hosted on github. Proposal: move the edit link in a small anchor in the footer (right beside the source url).

**Review by waltminer — APPROVED** [review]
Looks good to me. I like having the edit button there directly, but let's see how it goes.

**Pull request merged**
