### PR TITLE
Getting Started with AGL on QEMU, Porter and Raspberry Pi

### PR DESCRIPTION
**Pull request by leon-anavi**
Hi,

This GitHub request contains markdown files with documentation for getting started with QEMU, Renesas Porter board and Raspberry Pi 2/3. A bash script that wraps pandoc is responsible for merging together all files and making a single document per each board. The supported formats are HTML, PDF and DokuWiki (because this is the engine that powers AGL wiki).

Best regards, Leon

### CODE REVIEW

**Comment by kooltux** [comment]
I'd suggest to put your documentation files in a subdirectory named 'getting-started' or something equivalent, representing a kind of section in a whole documentation site.

For tools, like agldoc.sh, I suggest to put them in a subdir 'doctools'. In particular for agldoc.sh, I think that having a more generic script would be great: so why specifying the machine ? Just specify the output format and the input file(s). For example, I also wrote a quick command to convert any md files in a directory to dokuwiki for my own goals (importing into the wiki). But it would be better to have a more generic tool and your script seems well fitted for that: it can already export in PDF, dokuwiki etc.

**Comment by leon-anavi** [comment]
Hi @kooltux,

I have applied the recommended changes. Please have a look at the latest commit.

Best regards, Leon

**Comment by kooltux** [comment]
Hi Leon. Thanks for update. 
I didn't have a detailed look at your script agldoc.sh : it seems that it works only with your 'getting-started' guides, right ? If that's the case, I'd move it to the 'getting-started' directory. Otherwise, keep it in doctools, but make it generic by removing hardcoded path names and machine: the tool is only a convenience to convert a markdown file to something else after all: I mean it should work for any document, not only those you commit now.

**Comment by leon-anavi** [comment]
Hi @kooltux,

Yes, the existing script is very specific for the "Getting Started" guidelines because it combines several files in exact order to generate a single document per board:
- General instructions for downloading the source
- Instructions for setting the build environment depending on the board
- Instructions for booting AGL image on the board
- General troubleshooting guidelines
- Board specific notes

I really liked your previous suggestion about directory doctools. Let's have all tools there. Will it be OK if I keep the script in directory doctools and rename it to generate-getting-started.sh?

Thanks, Leon

**Comment by kooltux** [comment]
Sure ! We can make it more generic later...

**Comment by leon-anavi** [comment]
Hi @kooltux ,

I have renamed the script to generate-getting-started.sh and submitted the change as another GitHub pull request: https://github.com/automotive-grade-linux/docs-agl/pull/7

Thanks, Leon

**Pull request merged**
