### PR TITLE
Update toc_dev_en.yml and fetched_files.yml

### PR DESCRIPTION
**Pull request by hiroshi-kojima**
To add HMI-FW documents (HS, WM, SM), add these information to "APIs&Services" section.

Signed-off-by: hkojima <hiroshi_kojima@mentor.com>

### CODE REVIEW

**Comment by claneys** [comment]
You should take your documentation source from gerrit not your github repo as this duplicate ApplicationGuide.md from gerrit repo.
Look at an example here : https://github.com/claneys/docs-agl/commit/f5b15d93b811be8ac7be60279aa219ce99179a6e

**Comment by hiroshi-kojima** [comment]
I changed "url_fetch" from github to gerrit.
And also "git_name" and "src_prefix" since directory structure is different between github and gerrit.

**Comment by claneys** [comment]
Great, looks good to me.
Thanks

**Comment by claneys** [comment]
Oups, testing it and see some creepy html tag in index of homescreen guide and soundmanager:
example:
<div id="Table\ of\ content">Table of content</div>

Could you clean them please.

**Comment by hiroshi-kojima** [comment]
Because "git_commit" set as "master" so currently it refer to "RC1" documentation.
Latest documentation for RC2 have already fix it. So I believe after current HS/WM/SM code review is finished, it will be fix automatically.

**Comment by claneys** [comment]
Ok, great then :)

**Pull request merged**
