### PR TITLE
R-Car-Starter-Kit-gen3.md: Talk about wic images now

### PR DESCRIPTION
**Pull request by trini**
With Eel we now provide wic images, so there's no reason to have all of
the steps involving extracting a tarball manually onto a manually
prepared SD card.

Bug-AGL: SPEC-899
Signed-off-by: Tom Rini <trini@konsulko.com>

### CODE REVIEW

**Comment by jobol** [comment]
I'm fully confortable with using tar that copies just what is needed. The new procedure will make lose time and space on the SDCARD. But I agree that it is cool for newbies. Where is the documentation about wic? I didn't found one on Internet?

**Comment by cajun-rat** [comment]
As someone scared by the long instructions before, I like this :)

It is also quite simple to extend the partition to take up all the available space on the SD card:

~~~
sudo parted -s /dev/sdX resizepart 2 '100%' 
sudo resize2fs /dev/sdX2
~~~

**Comment by kooltux** [comment]
@jobol using wic and bmap is far better for distributing images to people who don't have much skills. Also, what about a guy under windows ? I prefer him to pick an imager and use the raw image than running tar !

**Comment by trini** [comment]
@jobol I'd be interested in seeing a 'time' on old vs new, but I'm pretty sure dd is about the same, or faster (since there's no filesystem operations to worry about on top of block operations).
@cajun-rat Yes, a high level wish of mine is that once we are able to get things consistent and shared for all platforms (all platforms have and use wic now) that we add in 'advanced tips' such as resizing if the user needs it.
@kooltux telling people to use bmaptool on top of things is another on the list of things to do, once we would not be copy/pasting the exact same information between each machine as it's all common process.

**Comment by kooltux** [comment]
@trini : agreed. FYI, we have binary packages for bmap-tools for common linux distros here: https://build.opensuse.org/package/show/isv:LinuxAutomotive:app-Development/bmap-tools (warning: debian/ubuntu packages are broken ATM)

**Comment by kooltux** [comment]
@trini , I had a look at your changes in the markdown: there's a typo somewhere when quoting some script and the result is not very readable. Check for example the result here: https://github.com/konsulko/docs-agl/blob/459dfcffd6930681fc800f75eb8910971a9d42f1/docs/getting-started/machines/R-Car-Starter-Kit-gen3.md#configure-u-boot-parameters

**Comment by trini** [comment]
@kooltux Can you give me a hint?  I only see the usual problems related to markdown github can't handle.  Doing a:
./doctools/generate-getting-started.sh -m R-Car-Starter-Kit-gen3
and throwing the HTML at FIrefox looks right.  Thanks!

**Comment by kooltux** [comment]
generate-getting-started.sh use pandoc, github uses kramdown and that's always the same story...

From what I see, it's an issue with indentation: you should align your first lines (often with the prompt '=>') with the rest of the quoted paragraph, like this
<pre>
    ```bash
....=> printenv
 ^  baudrate=115200
 |  bootargs=console=ttySC0,115200 root=/dev/mmcblk1p1 rootwait ro rootfstype=ext4
 |  bootcmd=run load_ker; run load_dtb; booti 0x48080000 - 0x48000000
 |  bootdelay=3
 |  ...
 \--- here
</pre>

**Comment by kooltux** [comment]
@trini : quick feedback on runtime tests given the recent addition ytou made [in this commit](https://git.automotivelinux.org/AGL/meta-agl/commit/?h=sandbox/ohporter/kf-v2.23.1-pyro&id=7fc4ae90797a085a06730201bfe404612fb72a21).
Everything seems ok in the image (I mean: the file boot/boot.scr is there and contains something meaningful). But on uboot side, I get an issue when runing the bootcmd that tries to source the script
If I do it manually:
<pre>
=> version

U-Boot 2015.04 (Oct 11 2017 - 20:47:11)
aarch64-agl-linux-gcc (GCC) 6.3.0
GNU ld (GNU Binutils) 2.28.0.20170307
=> env default -a
## Resetting to default environment
=> setenv fdtfile devicetree-Image-r8a7796-m3ulcb.dtb
=> ext4load mmc 0:1 0x48070000 /boot/boot.scr
273 bytes read in 6 ms (43.9 KiB/s)
=> source 0x48070000
Unknown command 'source' - try 'help'
=>
</pre>

I don't know why the 'source' command is not available in the uboot that I built and flashed very recently (Oct 11 2017) on my board... Maybe a configure option that was dropped at some point ?
Don't you have the same issue ?

**Comment by trini** [comment]
@kooltux I've got this split into two different commits and branches :)  The 'source' command comes when you've built and flashed an updated U-Boot from the KF branch, so I've got that over in a different branch (and you'll need to flash in new ATF/Op-tee for newer U-Boot to work).  And I'll go re-check the indentation on my updates there, thanks!

**Comment by kooltux** [comment]
@trini got it. Thx for heads up.

**Comment by kooltux** [comment]
Just one minor thing: I saw that the device tree files are now named "devicetree-Image-\*.dtb" in wic images instead of "Image-\*.dtb" previously (as they are stored in deploy/images). Is it on purpose, or could you rename them as "before" ? Many people have uboot configs which point to "Image-*.dtb" and which will fail with wic images. If we want people to adopt wic format, we should make their life easier...

**Comment by trini** [comment]
@kooltux I don't quite follow, sorry.  I've been using wic images with the previous instructions and U-Boot variables for a while just fine.  We don't change the boot instructions until KF support comes in, as that's a chance to have the user change their env anyhow.

**Comment by kooltux** [comment]
@trini: yes the new instructions for SD card will work. But for netboot mode, it would be more convenient to have the same name as the file in the tmp/deploy folder: you can simply export the deployment folder and you're done. Otherwise you'll have to to some renaming, or adjust uboot config for netboot

**Comment by trini** [comment]
@kooltux yes, it's unfortunate that we don't at this point in time have a way to determine which board we're on at run-time and grab the correct DTB as is done on many other platforms.  But for netboot, that's still a separate situation as it always has been.

**Comment by waltminer** [comment]
@trini Please resolve merge conflicts. @kooltux is your review for this change -1?  I see a lot of comments but no review.

**Comment by kooltux** [comment]
@trini: for netboot, that will differ for sure, as the DTB must be loaded from tftp, not from the filesystem itself. So the boot script can't be used from the filesystem. We can probably pull it from tftp. Again, naming files accordingly is needed. What we do usually is that the tmp/deploy/m3ulcb folder is exposed though TFTP (zero copy). But we could imagine an extra step while building for netboot to create a folder to be exposed as TFTP. What do you think ?
I'd review +1 but there's a conflict to solve.

**Comment by dl9pf** [comment]
After rebase, this doc-update is fine. The devicetree issue needs to be solved (aka we should not rename files 'again') but this does not affect this part of the documentation thus it is unrelated to the doc update.

**Comment by trini** [comment]
@waltminer @dl9pf I've pushed a new version rebased onto master.
@kooltux @dl9pf I would most certainly welcome an update to these docs that documents using netboot as I've always been pointed at https://github.com/openivimobility/meta-agl/tree/master/meta-netboot as the canonical doc, and since that's about porter, it's a tad out of date now :)  There's no reason we can't have zero copy docs and have it be more generic so it's correct for any board as everyone has wic, and everyone has the same named pattern for device tree files.

**Comment by kooltux** [comment]
@trini the READMEs [here](https://git.automotivelinux.org/AGL/meta-agl/tree/meta-netboot) are more accurate than the one you pointed, but not completely up-to-date. In particular, the uboot config for gen3 works for both mmc and netboot, if minor adjustments are made to dtb file names.

**Comment by trini** [comment]
@kooltux OK, thanks.  I'll just put on my wishlist more concise and reusable docs for that step, as a future thing.

**Comment by dl9pf** [comment]
So while we can still add more example cmdlines for the endless number of $BOARD, I think the README in meta-netboot is fine as a starter.

Note that as we're using nbd, we will still share the ext4  and /dev/nbd0 . A boot with a *partitioned image* (like .wic is ) still needs to be enabled/tested. Patches welcome.

So back to this document.  +1. Lets go and fry the other fish.

**Review by dl9pf — APPROVED** [review]
+1

**Comment by kooltux** [comment]
Just wondering... Could it be possible to "mount" a wic image through nbd (=make it recognized as a virtual disk) ? That would allow an interesting unification :)

**Comment by trini** [comment]
@kooltux Yes, there's no reason it shouldn't be able to be, it's all just a block device to the kernel.  You can losetup -P (or losetup and partprobe /dev/loopX) on the host or nbd it out or whatever.  You could maybe even do some iSCSI magic if you were sufficiently motivated :)

**Comment by kooltux** [comment]
Yes. iSCSI was one possible solution but at the end nbd was simpler. At the end, mounting the same wic image is interesting for CI & QA: you're (quite) guaranteed to have the same bytes mounted. That's just nice!

**Pull request merged**
