### PR TITLE
Add initial homescreen documentation

### PR DESCRIPTION
**Pull request by jensbocklage**
Just an introduction with some screenshots

Signed-off-by: Bocklage, Jens <Jens_Bocklage@mentor.com>

### CODE REVIEW

**Comment by kooltux** [comment]
Should we put it in the "Getting started" section or in "API/Services" ? Otherwise, seems ok.

**Comment by jensbocklage** [comment]
I wanted to have a short introduction in the Getting started section. Not too much technical detail here. The HomeScreen API will be hosted in API/Services. I talked to Jan-Simon about this.

**Comment by dl9pf** [comment]
LGTM.

**Comment by kooltux** [comment]
OK. Let's go like this then :)

**Pull request merged**
